export const topics = [
    {   _id: '1',
        title: 'Family',
        alias: 'family',
        image: 'https://cdn2.iconfinder.com/data/icons/architecture-interior/24/architecture-interior-01-512.png',
        tips: 'List of tips'},
    {   _id: '2',
        title: 'Travels & vacation',
        alias: 'travel-vacation',
        image: 'https://cdn1.iconfinder.com/data/icons/locations-redesign/48/Plane_Tickets1-512.png',
        tips: 'List of tips'},
    {   _id: '3',
        title: 'Hobbies & games',
        alias: 'hobbies-games',
        image: 'https://cdn1.iconfinder.com/data/icons/locations-redesign/48/Games1-512.png',
        tips: 'List of tips'},
    {   _id: '4',
        title: 'Food & cuisines',
        alias: 'food-cuisines',
        image: 'https://cdn1.iconfinder.com/data/icons/food-and-drink-vol-1-1/512/2-512.png',
        tips: 'List of tips'},
    {   _id: '5',
        title: 'Traffic & transport',
        alias: 'traffic-transportation',
        image: 'https://cdn4.iconfinder.com/data/icons/aiga-symbol-signs/612/aiga_ground_transportation_bg-512.png',
        tips: 'List of tips'},
    {   _id: '6',
        title: 'Occupations & jobs',
        alias: 'occupations-jobs',
        image: 'https://cdn4.iconfinder.com/data/icons/miu/24/business-suitcase-glyph-512.png',
        tips: 'List of tips'},
    {   _id: '7',
        title: 'Exploring a city',
        alias: 'city',
        image: 'https://cdn1.iconfinder.com/data/icons/building-vol-3-3/512/16-512.png',
        tips: 'List of tips'},
    {   _id: '8',
        title: 'Weather',
        alias: 'weather',
        image: 'https://cdn0.iconfinder.com/data/icons/typicons-2/24/weather-partly-sunny-512.png',
        tips: 'List of tips'},
];